from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage

from opticlaw.connectors.base import Connector, ConnectorResult


class EmailConnector(Connector):
    name = "email"

    async def run(self, instruction: str) -> ConnectorResult:
        params = self._parse_instruction(instruction)
        to_addr = params.get("to")
        subject = params.get("subject", "OptiClaw draft")
        body = params.get("body", "Generated by OptiClaw")

        if not to_addr:
            return ConnectorResult(False, "[email] missing to=<recipient>")

        smtp_host = os.getenv("OPTICLAW_SMTP_HOST")
        smtp_port = int(os.getenv("OPTICLAW_SMTP_PORT", "587"))
        smtp_user = os.getenv("OPTICLAW_SMTP_USER")
        smtp_pass = os.getenv("OPTICLAW_SMTP_PASS")
        from_addr = os.getenv("OPTICLAW_SMTP_FROM", smtp_user or "opticlaw@localhost")

        if not (smtp_host and smtp_user and smtp_pass):
            return ConnectorResult(
                True,
                f"[email-dry-run] to={to_addr} subject={subject} body={body[:80]}",
            )

        msg = EmailMessage()
        msg["From"] = from_addr
        msg["To"] = to_addr
        msg["Subject"] = subject
        msg.set_content(body)

        try:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
                server.starttls()
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)
            return ConnectorResult(True, f"[email] sent to {to_addr}")
        except Exception as exc:
            return ConnectorResult(False, f"[email] send failed: {exc}")

    @staticmethod
    def _parse_instruction(instruction: str) -> dict[str, str]:
        parts = [p.strip() for p in instruction.split(";") if p.strip()]
        parsed: dict[str, str] = {}
        for part in parts:
            if "=" not in part:
                continue
            key, value = part.split("=", 1)
            parsed[key.strip().lower()] = value.strip()
        return parsed
